# fish completion for ssherpa

complete -c ssherpa -f -n '__fish_use_subcommand' -a add -d 'Add or update an SSH alias'
complete -c ssherpa -f -n '__fish_use_subcommand' -a edit -d 'Edit or delete SSH aliases'
complete -c ssherpa -f -n '__fish_use_subcommand' -a jump -d 'Connect through ProxyJump hops'
complete -c ssherpa -f -n '__fish_use_subcommand' -a proxy -d 'Start a local SOCKS proxy'
complete -c ssherpa -f -n '__fish_use_subcommand' -a forward -d 'Open and manage port-forward tunnels'
complete -c ssherpa -f -n '__fish_use_subcommand' -a send -d 'Send a local file with SFTP'
complete -c ssherpa -f -n '__fish_use_subcommand' -a receive -d 'Receive a remote file with SFTP'
complete -c ssherpa -f -n '__fish_use_subcommand' -a check -d 'Test SSH aliases and saved forwards'
complete -c ssherpa -f -n '__fish_use_subcommand' -a authkeys -d 'Manage authorized_keys'
complete -c ssherpa -f -n '__fish_use_subcommand' -a theme -d 'Build and save UI colors'
complete -c ssherpa -f -n '__fish_use_subcommand' -a session -d 'Inspect session records'
complete -c ssherpa -f -n '__fish_use_subcommand' -a list -d 'List SSH aliases'
complete -c ssherpa -f -n '__fish_use_subcommand' -a show -d 'Show one SSH alias'
complete -c ssherpa -f -n '__fish_use_subcommand' -a version -d 'Print build version'
complete -c ssherpa -f -n '__fish_use_subcommand' -a help -d 'Show help'

complete -c ssherpa -n '__fish_seen_subcommand_from check' -l json -d 'Emit JSON'
complete -c ssherpa -n '__fish_seen_subcommand_from check' -l config -r -d 'Read SSH config'
complete -c ssherpa -n '__fish_seen_subcommand_from check' -l state-dir -r -d 'Override state directory'
complete -c ssherpa -n '__fish_seen_subcommand_from check' -l ssh-binary -r -d 'Use this SSH binary'
complete -c ssherpa -n '__fish_seen_subcommand_from check' -l timeout -r -d 'SSH probe timeout'
complete -c ssherpa -n '__fish_seen_subcommand_from check' -l icmp-timeout -r -d 'ICMP timeout'
complete -c ssherpa -n '__fish_seen_subcommand_from check' -l no-icmp -d 'Skip ICMP ping'
complete -c ssherpa -n '__fish_seen_subcommand_from check' -l saved-forward -r -d 'Check saved forward'
complete -c ssherpa -n '__fish_seen_subcommand_from check' -l saved-forwards -d 'Check all saved forwards'

complete -c ssherpa -n '__fish_seen_subcommand_from send' -l select -r -d 'SSH alias'
complete -c ssherpa -n '__fish_seen_subcommand_from send' -l remote -r -d 'Remote destination path'
complete -c ssherpa -n '__fish_seen_subcommand_from send' -l config -r -d 'Read SSH config'
complete -c ssherpa -n '__fish_seen_subcommand_from send' -l sftp-binary -r -d 'Use this SFTP binary'
complete -c ssherpa -n '__fish_seen_subcommand_from send' -l print -d 'Print command'

complete -c ssherpa -n '__fish_seen_subcommand_from receive' -l select -r -d 'SSH alias'
complete -c ssherpa -n '__fish_seen_subcommand_from receive' -l local -r -d 'Local destination path'
complete -c ssherpa -n '__fish_seen_subcommand_from receive' -l config -r -d 'Read SSH config'
complete -c ssherpa -n '__fish_seen_subcommand_from receive' -l sftp-binary -r -d 'Use this SFTP binary'
complete -c ssherpa -n '__fish_seen_subcommand_from receive' -l print -d 'Print command'

complete -c ssherpa -n '__fish_seen_subcommand_from forward' -a 'list status stop saved'
complete -c ssherpa -n '__fish_seen_subcommand_from forward; and __fish_contains_opt saved' -a 'list show save edit delete rename'
complete -c ssherpa -n '__fish_seen_subcommand_from forward' -l select -r -d 'SSH alias or saved forward'
complete -c ssherpa -n '__fish_seen_subcommand_from forward' -l local -r -d 'Local bind/port'
complete -c ssherpa -n '__fish_seen_subcommand_from forward' -l remote -r -d 'Remote host/port'
complete -c ssherpa -n '__fish_seen_subcommand_from forward' -l through -r -d 'Jump alias'
complete -c ssherpa -n '__fish_seen_subcommand_from forward' -l background -d 'Run detached'
complete -c ssherpa -n '__fish_seen_subcommand_from forward' -l state-dir -r -d 'Override state directory'

complete -c ssherpa -n '__fish_seen_subcommand_from proxy' -a 'list status stop saved'
complete -c ssherpa -n '__fish_seen_subcommand_from proxy; and __fish_contains_opt saved' -a 'list show save edit delete rename'
complete -c ssherpa -n '__fish_seen_subcommand_from proxy' -l select -r -d 'SSH alias or saved proxy'
complete -c ssherpa -n '__fish_seen_subcommand_from proxy' -l bind -r -d 'Listener bind address'
complete -c ssherpa -n '__fish_seen_subcommand_from proxy' -l port -r -d 'Listener port'
complete -c ssherpa -n '__fish_seen_subcommand_from proxy' -l background -d 'Run detached'
complete -c ssherpa -n '__fish_seen_subcommand_from proxy' -l state-dir -r -d 'Override state directory'

complete -c ssherpa -n '__fish_seen_subcommand_from session' -a 'list map show stop-all prune'
complete -c ssherpa -n '__fish_seen_subcommand_from session' -l json -d 'Emit JSON'
complete -c ssherpa -n '__fish_seen_subcommand_from session' -l all -d 'Include exited sessions'
complete -c ssherpa -n '__fish_seen_subcommand_from session' -l state-dir -r -d 'Override state directory'
complete -c ssherpa -n '__fish_seen_subcommand_from session' -l older-than -r -d 'Prune records older than duration'
complete -c ssherpa -n '__fish_seen_subcommand_from session' -l dry-run -d 'Preview prune'
